### ISSUE TITLE
Add a CONTRIBUTING.md file to repository

### ISSUE THREAD

**Issue by cs-cordero** [silviogutierrez/reactivated#16]
Examples:
* https://github.com/psf/black/blob/master/CONTRIBUTING.md
* https://github.com/django/django/blob/master/CONTRIBUTING.rst
* https://github.com/python/mypy/blob/master/CONTRIBUTING.md
* https://github.com/psf/requests/blob/master/CONTRIBUTING.md

**Comment by silviogutierrez** [comment]
Feel free to open a PR!
