### ISSUE TITLE
Nix install `Error: Could not find a version that satisfies the requirement reactivated==0.27.2`

### ISSUE THREAD

**Issue by devo-wm** [silviogutierrez/reactivated#221]
Loving the single command install!

However, I think the latest version may not have published properly to pip

Here's a link to the full output if you need: https://gist.github.com/devo-wm/c0a28828757e4c58efeace677de6556d

**Comment by MattGaiser** [comment]
Doing a workaround by downgrading the `requirements.txt` to 0.27.1 leads to this error:

`node_modules/_reactivated/index.tsx:804:40 - error TS2339: Property 'models' does not exist on type '{ Widget: DjangoFormsWidgetsTextInput | DjangoFormsWidgetsNumberInput | DjangoFormsWidgetsHiddenInput | ... 6 more ... | DjangoFormsWidgetsCheckboxInput; }'.

804 export type models = _Types["globals"]["models"];
                                           ~~~~~~~~
`

**Comment by silviogutierrez** [comment]
Thanks for the heads up, I'll investigate.

**Comment by silviogutierrez** [comment]
@devo-wm @MattGaiser : thanks for the info. The build process was broken but it's since been resolved. It should be working now.
