### ISSUE TITLE
Basic Setup Failing

### ISSUE THREAD

**Issue by MaxWason** [silviogutierrez/reactivated#305]
Not sure if the project is still live and being worked on (it looks very promising!) but trying to build via the [official instructions ](https://www.reactivated.io/documentation/getting-started/) had a host of errors for me.

Specifically, these look like potential sources of issues:

`bash: lesspipe: command not found`

`Cannot find package 'ts-morph'`

`ESLint couldn't find the plugin "eslint-plugin-react".`
`Cannot find package '@vanilla-extract/esbuild-plugin'`

`This is not the tsc command you are looking for`
`To get access to the TypeScript compiler, tsc, from the command line either:`
`- Use npm install typescript to first add TypeScript to your project before using npx`
`- Use yarn to avoid accidentally running code from un-installed packages`

Then, when trying to open `localhost:8000`, there was no connection ('Unable to connect')

Let me know if you need any additional info; I'd love to get this working if possible!

<details><summary>Full Terminal Output</summary>
<p>

max@max-desktop:~$ cd Documents/
max@max-desktop:~/Documents$ ls
 GitHub  'HW Manager'   LocalCode
max@max-desktop:~/Documents$ cd GitHub/
max@max-desktop:~/Documents/GitHub$ nix-shell -E "$(curl -L https://reactivated.io/install/)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   434  100   434    0     0    268      0  0:00:01  0:00:01 --:--:--     0
Enter a project name
DemoReactivated
Initialized empty Git repository in /home/max/Documents/GitHub/DemoReactivated/.git/
bash: lesspipe: command not found
Wrote to /home/max/Documents/GitHub/DemoReactivated/package.json:

{
  "name": "demoreactivated",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

bash: lesspipe: command not found

added 1 package, and audited 2 packages in 732ms

found 0 vulnerabilities
bash: lesspipe: command not found
created virtual environment CPython3.9.13.final.0-64 in 284ms
  creator CPython3Posix(dest=/home/max/Documents/GitHub/DemoReactivated/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/max/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==61.0.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Collecting Django==4.0.1
  Using cached Django-4.0.1-py3-none-any.whl (8.0 MB)
Collecting psycopg2-binary==2.9.3
  Using cached psycopg2_binary-2.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting simplejson==3.16.0
  Using cached simplejson-3.16.0-cp39-cp39-linux_x86_64.whl
Collecting django-stubs==1.9.0
  Using cached django_stubs-1.9.0-py3-none-any.whl (401 kB)
Collecting mypy==0.910
  Using cached mypy-0.910-cp39-cp39-manylinux2010_x86_64.whl (23.2 MB)
Collecting black==22.3.0
  Using cached black-22.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
Collecting isort==5.10.1
  Using cached isort-5.10.1-py3-none-any.whl (103 kB)
Collecting pytest==6.2.5
  Using cached pytest-6.2.5-py3-none-any.whl (280 kB)
Collecting pytest-django==4.5.2
  Using cached pytest_django-4.5.2-py3-none-any.whl (20 kB)
Collecting flake8==4.0.1
  Using cached flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting autoflake==1.4
  Using cached autoflake-1.4-py3-none-any.whl
Collecting gunicorn==20.1.0
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting dj-database-url==0.5.0
  Using cached dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting reactivated==0.33.1
  Using cached reactivated-0.33.1-py3-none-any.whl (81 kB)
Collecting asgiref<4,>=3.4.1
  Using cached asgiref-3.7.2-py3-none-any.whl (24 kB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)
Collecting types-pytz
  Using cached types_pytz-2023.3.1.1-py3-none-any.whl (4.9 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting types-PyYAML
  Using cached types_PyYAML-6.0.12.12-py3-none-any.whl (14 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting django-stubs-ext>=0.3.0
  Using cached django_stubs_ext-4.2.7-py3-none-any.whl (8.9 kB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.4-py2.py3-none-any.whl
Collecting click>=8.0.0
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Requirement already satisfied: platformdirs>=2 in /nix/store/0njw1jhx2azm9v0a9rjkmgzfrmp89m7c-python3.9-platformdirs-2.5.2/lib/python3.9/site-packages (from black==22.3.0->-r requirements.txt (line 6)) (2.5.2)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pathspec>=0.9.0
  Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Collecting attrs>=19.2.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Collecting iniconfig
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting pycodestyle<2.9.0,>=2.8.0
  Using cached pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.5.0,>=2.4.0
  Using cached pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
Requirement already satisfied: setuptools>=3.0 in ./.venv/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 13)) (61.0.0)
Collecting requests-unixsocket==0.3.0
  Using cached requests_unixsocket-0.3.0-py2.py3-none-any.whl (11 kB)
Collecting requests==2.25.0
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Installing collected packages: types-PyYAML, types-pytz, mccabe, dj-database-url, chardet, urllib3, typing-extensions, tomli, toml, sqlparse, simplejson, pyflakes, pycodestyle, py, psycopg2-binary, pluggy, pathspec, packaging, mypy-extensions, isort, iniconfig, idna, gunicorn, click, certifi, attrs, requests, pytest, mypy, flake8, black, autoflake, asgiref, requests-unixsocket, pytest-django, Django, reactivated, django-stubs-ext, django-stubs
Successfully installed Django-4.0.1 asgiref-3.7.2 attrs-23.1.0 autoflake-1.4 black-22.3.0 certifi-2023.11.17 chardet-3.0.4 click-8.1.7 dj-database-url-0.5.0 django-stubs-1.9.0 django-stubs-ext-4.2.7 flake8-4.0.1 gunicorn-20.1.0 idna-2.10 iniconfig-2.0.0 isort-5.10.1 mccabe-0.6.1 mypy-0.910 mypy-extensions-0.4.4 packaging-23.2 pathspec-0.12.1 pluggy-1.3.0 psycopg2-binary-2.9.3 py-1.11.0 pycodestyle-2.8.0 pyflakes-2.4.0 pytest-6.2.5 pytest-django-4.5.2 reactivated-0.33.1 requests-2.25.0 requests-unixsocket-0.3.0 simplejson-3.16.0 sqlparse-0.4.4 toml-0.10.2 tomli-2.0.1 types-PyYAML-6.0.12.12 types-pytz-2023.3.1.1 typing-extensions-4.9.0 urllib3-1.26.18

[notice] A new release of pip available: 22.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
The files belonging to this database system will be owned by user "max".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/max/Documents/GitHub/DemoReactivated/.venv/postgresql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /nix/store/axji8ka65rx9pp5l5ga4k8bng730xg30-postgresql-13.7/bin/pg_ctl -D /home/max/Documents/GitHub/DemoReactivated/.venv/postgresql -l logfile start

[12/Dec/2023 23:32:29,778] Generating interfaces and client side code
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-morph' imported from /home/max/Documents/GitHub/DemoReactivated/node_modules/reactivated/dist/generator.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-morph' imported from /home/max/Documents/GitHub/DemoReactivated/node_modules/reactivated/dist/generator/constants.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
[12/Dec/2023 23:32:30,413] Finished generating.
bash: lesspipe: command not found
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, example, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying example.0001_initial... OK
  Applying sessions.0001_initial... OK
bash: lesspipe: command not found
Running against all git files
[Python]:
manage.py
server/__init__.py
server/asgi.py
server/example/__init__.py
server/example/admin.py
server/example/apps.py
server/example/context_processors.py
server/example/forms.py
server/example/migrations/0001_initial.py
server/example/migrations/__init__.py
server/example/models.py
server/example/templates.py
server/example/tests.py
server/example/urls.py
server/example/views.py
server/settings/__init__.py
server/settings/common.py
server/settings/localhost.py
server/settings/production.py
server/urls.py
server/wsgi.py

[Prettier]:
.eslintrc.json
client/components/Layout.tsx
client/forms.tsx
client/index.tsx
client/styles.tsx
client/templates/DjangoDefault.tsx
client/templates/EditPoll.tsx
client/templates/FormPlayground.tsx
client/templates/PollComments.tsx
client/templates/PollDetail.tsx
client/templates/PollsIndex.tsx
client/templates/Results.tsx
package-lock.json
package.json
tsconfig.json

[TypeScript/JS]:
client/components/Layout.tsx
client/forms.tsx
client/index.tsx
client/styles.tsx
client/templates/DjangoDefault.tsx
client/templates/EditPoll.tsx
client/templates/FormPlayground.tsx
client/templates/PollComments.tsx
client/templates/PollDetail.tsx
client/templates/PollsIndex.tsx
client/templates/Results.tsx

[Shell]:
scripts/deploy.sh
scripts/fix.sh
scripts/helpers.sh
scripts/launch.sh
scripts/remove_example.sh
scripts/test.sh

[Nix]:
requirements.nix
shell.nix

[Terraform]:

All done! ✨ 🍰 ✨
21 files left unchanged.

Oops! Something went wrong! :(

ESLint: 8.55.0

ESLint couldn't find the plugin "eslint-plugin-react".

(The package "eslint-plugin-react" was not found when loaded as a Node module from the directory "/home/max/Documents/GitHub/DemoReactivated".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-react@latest --save-dev

The plugin "eslint-plugin-react" was referenced from the config file in ".eslintrc.json » ./node_modules/reactivated/dist/eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

.eslintrc.json 50ms (unchanged)
client/components/Layout.tsx 253ms (unchanged)
client/forms.tsx 24ms (unchanged)
client/index.tsx 6ms (unchanged)
client/styles.tsx 15ms (unchanged)
client/templates/DjangoDefault.tsx 30ms
client/templates/EditPoll.tsx 22ms (unchanged)
client/templates/FormPlayground.tsx 9ms (unchanged)
client/templates/PollComments.tsx 24ms (unchanged)
client/templates/PollDetail.tsx 18ms (unchanged)
client/templates/PollsIndex.tsx 11ms (unchanged)
client/templates/Results.tsx 6ms (unchanged)
package-lock.json 5ms
package.json 1ms
tsconfig.json 2ms (unchanged)
[main (root-commit) 1dc0930] Initial files
 56 files changed, 2141 insertions(+)
 create mode 100644 .dockerignore
 create mode 100644 .editorconfig
 create mode 100644 .eslintrc.json
 create mode 100644 .flake8
 create mode 100644 .gitignore
 create mode 100644 .isort.cfg
 create mode 100644 .prettierrc
 create mode 100644 .shellcheckrc
 create mode 100644 Dockerfile
 create mode 100644 client/components/Layout.tsx
 create mode 100644 client/forms.tsx
 create mode 100644 client/index.tsx
 create mode 100644 client/styles.tsx
 create mode 100644 client/templates/DjangoDefault.tsx
 create mode 100644 client/templates/EditPoll.tsx
 create mode 100644 client/templates/FormPlayground.tsx
 create mode 100644 client/templates/PollComments.tsx
 create mode 100644 client/templates/PollDetail.tsx
 create mode 100644 client/templates/PollsIndex.tsx
 create mode 100644 client/templates/Results.tsx
 create mode 100755 manage.py
 create mode 100644 mypy.ini
 create mode 100644 package-lock.json
 create mode 100644 package.json
 create mode 100644 pytest.ini
 create mode 100644 requirements.nix
 create mode 100644 requirements.txt
 create mode 100755 scripts/deploy.sh
 create mode 100755 scripts/fix.sh
 create mode 100644 scripts/helpers.sh
 create mode 100755 scripts/launch.sh
 create mode 100755 scripts/remove_example.sh
 create mode 100755 scripts/test.sh
 create mode 100644 server/__init__.py
 create mode 100644 server/asgi.py
 create mode 100644 server/example/__init__.py
 create mode 100644 server/example/admin.py
 create mode 100644 server/example/apps.py
 create mode 100644 server/example/context_processors.py
 create mode 100644 server/example/forms.py
 create mode 100644 server/example/migrations/0001_initial.py
 create mode 100644 server/example/migrations/__init__.py
 create mode 100644 server/example/models.py
 create mode 100644 server/example/templates.py
 create mode 100644 server/example/tests.py
 create mode 100644 server/example/urls.py
 create mode 100644 server/example/views.py
 create mode 120000 server/settings/__init__.py
 create mode 100644 server/settings/common.py
 create mode 100644 server/settings/localhost.py
 create mode 100644 server/settings/production.py
 create mode 100644 server/urls.py
 create mode 100644 server/wsgi.py
 create mode 100644 shell.nix
 create mode 100644 static/favicon.ico
 create mode 100644 tsconfig.json

All done. You can start your project by running

cd DemoReactivated
nix-shell
python manage.py runserver
max@max-desktop:~/Documents/GitHub$ psql
Password for user max: 
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "max"
max@max-desktop:~/Documents/GitHub$ cd DemoReactivated/
max@max-desktop:~/Documents/GitHub/DemoReactivated$ nix-shell 

[nix-shell:~/Documents/GitHub/DemoReactivated]$ python manage.py runserver
[12/Dec/2023 23:34:22,066] Generating interfaces and client side code
[12/Dec/2023 23:34:22,067] Skipping generation as nothing has changed
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vanilla-extract/esbuild-plugin' imported from /home/max/Documents/GitHub/DemoReactivated/node_modules/reactivated/dist/build.client.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vanilla-extract/esbuild-plugin' imported from /home/max/Documents/GitHub/DemoReactivated/node_modules/reactivated/dist/build.renderer.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

                                                                               
                This is not the tsc command you are looking for                
                                                                               

To get access to the TypeScript compiler, tsc, from the command line either:

- Use npm install typescript to first add TypeScript to your project before using npx
- Use yarn to avoid accidentally running code from un-installed packages

^CTraceback (most recent call last):
  File "/home/max/Documents/GitHub/DemoReactivated/manage.py", line 22, in <module>
    main()
  File "/home/max/Documents/GitHub/DemoReactivated/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute
    autoreload.check_errors(django.setup)()
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/reactivated/apps.py", line 179, in ready
    processes.start_renderer()
  File "/home/max/Documents/GitHub/DemoReactivated/.venv/lib/python3.9/site-packages/reactivated/processes.py", line 55, in start_renderer
    if match := re.match(r"RENDERER:([/.\w]+):LISTENING", output):
  File "/nix/store/r8hi2lpzycparplcq0y663c43866f9bz-python3-3.9.13/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/nix/store/r8hi2lpzycparplcq0y663c43866f9bz-python3-3.9.13/lib/python3.9/re.py", line 289, in _compile
    def _compile(pattern, flags):
KeyboardInterrupt

[nix-shell:~/Documents/GitHub/DemoReactivated]$ 

</p>
</details>

**Comment by silviogutierrez** [comment]
Hi @MaxWason ,

Project is very much alive! Thanks for the report — though I'm unable to reproduce.

I just tried the official instructions on a clean macOS install and a clean Debian VM install.

Moreover, all the automated tests run of both MacOS and Ubuntu clean installs and they appear to be passing.

Any more info you can provide? What OS/architecture are you using? Is this maybe a Windows/Linux Subsystem install?

In the meantime, try the [existing project instructions](https://www.reactivated.io/documentation/existing-projects/) to see if you can add it to a regular Django project.

Thanks!

**Comment by MaxWason** [comment]
Hey Silvio,

Interesting. I'm running Linux, specifically Kubuntu 22.04 as my main OS, so I assume that isn't the issue.

I'll try the existing project instructions; thanks for the alternate path forward. I don't currently have a great project for that, but I'll try it on some simple django-react templates.

Other things I could maybe try:
- Reinstalling nix and trying it again on a clean dir
- Trying to install it via docker instead of nix
- Open to suggestions

Happy to provide any more info you can think of/may need.

Thank you!

**Comment by silviogutierrez** [comment]
@MaxWason since you're on linux, you could also create a Linux docker container and setup nix *inside* that to give it a try.

But just straight docker could work.

The issue seems to be `lesspipe` is not found and everything else then fails after that, but I don't know how to diagnose that. Could be env or shell related.

I'll be closing this for now but if you have additional findings feel free to reopen.

**Comment by MaxWason** [comment]
Confirming just using docker instead of nix directly worked!

Most likely it is indeed some env/shell related issue, as you mentioned. Very strange, as this is a relatively 'clean'/new install of Ubuntu, but I'll look into it more when I get the chance.

Excited to now look around the framework in earnest; thanks again!

**Comment by silviogutierrez** [comment]
That's great! If I setup Parallels soon, I'll give Kubuntu a try to see.

**Comment by silviogutierrez** [comment]
Oh and if you want a walkthrough of some of the advanced AJAX/code generation features (undocumented), let me know and we can hop on a screen share.

**Comment by MaxWason** [comment]
Update:
- Install works on a Mac install, using nix and the same instructions, essentially confirming it is an env issue
- Tried some basic changes to try and fix it on Kubuntu, to no avail, but I'll update here if I fix it eventually

I'll let you know if/when I get to those features; I appreciate the offer!
