### ISSUE TITLE
Migrations not applying/can't exec into container

### ISSUE THREAD

**Issue by chinnuu05** [silviogutierrez/reactivated#328]
Hi, I am trying to use Reactivated with [django-tenants](https://django-tenants.readthedocs.io/en/latest/)

I'm unable to connect to my postgres database when using a custom database engine. 

My database connection is setup to use a custom engine (django-tenants) like this: 

```
db_from_env = dj_database_url.config(default="postgres:///database")
db_from_env['ENGINE'] = "django_tenants.postgresql_backend"

DATABASES = {
    "default": db_from_env
}
```

Looking at the docs it looks like nix-shell handles setting up my database environments variables and I'm just supposed to exec into my container with `docker exec -it my_app nix-shell` and run my migrate command from there. 

But trying to exec using nix-shell gives me `OCI runtime exec failed: exec failed: unable to start container process: exec: "nix-shell": executable file not found in $PATH: unknown`

If I remove the `db_from_env['ENGINE'] = "django_tenants.postgresql_backend"` my Docker deployment works and connects to the database, but adding an engine gives a 500 error.

![NVIDIA_Share_etL5bNlx9v](https://github.com/silviogutierrez/reactivated/assets/136545841/8dc78174-601a-4fe9-82a2-c74ede350685)

Any ideas? Have a feeling I'm doing something wrong with nix-shell/Docker.

**Comment by chinnuu05** [comment]
@silviogutierrez any thoughts on this?

Been stuck on this for days and it's the only thing stopping me from deploying

**Comment by silviogutierrez** [comment]
@chinnuu05 : the pre-built docker image is just for trying out Reactivated without committing to Nix. It can't really be modified very much.

I would try a regular Nix installation or or [adding it manually](https://www.reactivated.io/documentation/existing-projects/).

As for why it's failing: looks like your custom engine needs binaries that are not available to the Docker image. Because, really, it's just a very simple image to try out Reactivated.

**Comment by chinnuu05** [comment]
> @chinnuu05 : the pre-built docker image is just for trying out Reactivated without committing to Nix. It can't really be modified very much.
> 
> I would try a regular Nix installation or or [adding it manually](https://www.reactivated.io/documentation/existing-projects/).
> 
> As for why it's failing: looks like your custom engine needs binaries that are not available to the Docker image. Because, really, it's just a very simple image to try out Reactivated.

I ended up just ditching the $PGHOST/nix-shell database and going with a postgres image in my docker compose. Got it working fine this way.

Would I need to do any cleanup with nix to remove the old database? Sorry, I'm new to Nix and don't really understand all the .nix files

**Comment by Ivin0022** [comment]
hey @chinnuu05, I'm using django-tenants as well, I'm not using nix at all in my setup, I Basically used a python docker image and manually installed node in the same image, it works

**Comment by silviogutierrez** [comment]
@chinnuu05 : that'll work, but if you're using a bunch of docker images, consider just locally installing python and node into your machine and skipping docker altogether.

@Ivin0022 's approach will work too.

Don't worry too much about removing the old DB, it's tiny and only used locally.
