### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by boosh** [silviogutierrez/reactivated#330]
All examples on the docs website are just `[object Object],[object Object],[object Object]`
<img width="957" alt="Screenshot 2024-02-18 at 21 26 14" src="https://github.com/silviogutierrez/reactivated/assets/362148/160aca6c-60ab-431f-b5ee-47e0ce1b24e5">

**Comment by silviogutierrez** [comment]
Fixed. Thanks for pointing that out.
