### ISSUE TITLE
Issues integrating in existing Django App

### ISSUE THREAD

**Issue by knowsuchagency** [silviogutierrez/reactivated#348]
I was having issues integrating the project in my existing template so I decided to create a new django project from scratch to rule out as much as possible.

I created the following repo: https://github.com/knowsuchagency/hello_reactivated/

When running `python manage.py runserver` I'm getting

```
client/templates/Default.tsx:3:25 - error TS2306: File '/Users/stephanfitzpatrick/projects/hello_reactivated/node_modules/_reactivated/index.tsx' is not a module.

3 import {templates} from "@reactivated";
```

The content of `node_modules/_reactivated/index.tsx` is simply.

```
// Digest: b4231b936ca007529ec0cc1fc4926ea27e286c37
```

It seems something isn't being compiled?

alongside a screen recording of the issue I'm having:

https://github.com/silviogutierrez/reactivated/assets/11974795/1410ccd1-aa68-4c2d-b62f-f287747b0eae

**Comment by silviogutierrez** [comment]
Repro is helpful, thank you.

1. First is that your URL needs a name. This is an ongoing issue that will be fixed, but just add `name="home"` or something in `urls.py`. See #344.
2. Your `package.json` needs a `name` field.
3. The docs need updating, `client/index.tsx` needs `await` before `getTemplate` as it's async. I think that's it.

Can you give those a try? Worked for me.

**Comment by knowsuchagency** [comment]
Amazing, that worked! Thanks :)

**Comment by silviogutierrez** [comment]
Just updated the code and website to reflect all these changes.
