### ISSUE TITLE
Error in Setup process

### ISSUE THREAD

**Issue by rudranag** [silviogutierrez/reactivated#356]
![image](https://github.com/silviogutierrez/reactivated/assets/18360891/2a70f511-cf74-429d-a335-9ade8432ac60)

**Comment by silviogutierrez** [comment]
Hi there,

Use a project name that is a valid python package name. So ... `myproject`, 'djangoreact`, etc.

No hyphens or the like. I'll add a check to prevent this soon.

Let me know if it works!

**Comment by rudranag** [comment]
I have tried that also
Still same issue

**Comment by rudranag** [comment]
Sorry closed it by mistake

**Comment by rudranag** [comment]
I have tried that also
Still same issue

**Comment by dgrah50** [comment]
Hey, I just wanted to let you know that I had this same issue and it was an issue with Nix (https://github.com/NixOS/nix/issues/10375) . Updating Nix to the latest unstable version (https://nixos.org/manual/nix/stable/installation/upgrading) fixed the issue.

**Comment by silviogutierrez** [comment]
@dgrah50 : I just tried it on a MacOS VM, with

```
bash-3.2$ nix --version
nix (Nix) 2.20.5
```

And ran the `nix-shell -E "$(curl -L https://reactivated.io/install/)"`

And it worked fine. Trying to figure out what's the problem here.

```
bash-3.2$ sw_vers
ProductName:            macOS
ProductVersion:         13.6.6
BuildVersion:           22G630
```

**Comment by habdams** [comment]
Hello @silviogutierrez 
I also can't seem complete the installation, I keep getting the error in the image below.
![Screenshot from 2024-05-11 14-01-24](https://github.com/silviogutierrez/reactivated/assets/6120474/907e2fc4-1136-41f0-8725-8fccc187529c)

**Comment by silviogutierrez** [comment]
@habdams : indeed, per @dgrah50 it seems to be broken on the latest Nix release.

Can you try his comment / suggestion? Upgrade Nix to the latest unstable first, then try again?

https://nixos.org/manual/nix/stable/installation/upgrading#macos-multi-user

Working on a fix, but it's hard to replicate and diagnose.

**Comment by habdams** [comment]
Okay, I will attempt that. Thank you
